import { POLICY } from '@/lib/config'

export default function VerificationPage() {
  return <div className="page-width page-top prose-page">
    <div className="page-title"><span className="eyebrow">METHODOLOGY AND LIMITATIONS</span><h1>What “verified” means here</h1><p className="lead small">PriceGuard uses deterministic fixed-point arithmetic and independent validator web requests. It does not ask a model to guess whether a price looks plausible.</p></div>
    <section className="panel"><h2>Leader algorithm</h2><ol><li>Fetch fixed endpoints for Coinbase Exchange BTC-USD, Bitstamp BTC/USD, and Gemini BTC/USD.</li><li>Parse each response with source-specific code; users cannot supply URLs or prompts.</li><li>Reject malformed, non-positive, future-dated, or older-than-{POLICY.maxAgeSeconds}-second observations.</li><li>Convert decimal strings to integer cents without binary floating-point.</li><li>Exclude a source more than 100 bps from the preliminary three-source median and require at least {POLICY.refreshRequiredSources} accepted venues for a market refresh.</li><li>Return canonical JSON containing the accepted observations and every derived field.</li></ol></section>
    <section className="panel"><h2>Validator algorithm</h2><ol><li>Require the exact leader schema, symbol <code>BTC/USD</code>, and policy <code>{POLICY.version}</code>.</li><li>Recompute every leader-derived field from the raw source records.</li><li>Independently fetch and normalize the same fixed venues.</li><li>Reject if the leader and validator medians differ by more than {POLICY.validatorToleranceBps} bps.</li><li>For covenant evaluation, require all {POLICY.evaluationRequiredSources} sources, HIGH confidence, no circuit breaker, and the covenant’s own spread cap.</li></ol></section>
    <section className="panel"><h2>What an attestation does</h2><p>A satisfied evaluation records an immutable evidence certificate and moves the covenant to <code>TRIGGERED</code>. PriceGuard does not hold money, send funds, enforce a legal agreement, or execute an external business action. Integrators decide how to use the evidence.</p></section>
    <section className="panel"><h2>Bradbury deployment status</h2><p>PriceGuard V2 is active at <code>0x7B939483E69ada6d2ca37acd3684182Ed141F35F</code> on Bradbury chain 4221. Deployment transaction: <code>0x0bec3ce3653dab8e1135bf2a2b547816905c132d78dabfc1f998f898c3f6bf69</code>. The deployed source SHA-256 is <code>bdd0fac72f9659d76e03c04c60d55f1be4a46127da691fa9265cc77bd10b125a</code> from commit <code>645e49a73e32cc0fdb12fda459d0fc7fa3b4d8f9</code>. The supplied first-market-refresh reference is <code>0x7516d2370b7067d1cfbde1ee8ec21ca0294e85f3902ac2c0b9c702f5aba6b313</code>; its identifier type, finality, execution result, resulting market sequence, and matching state read are not preserved in repository evidence. The production frontend is <a href="https://price-oracle-delta.vercel.app">price-oracle-delta.vercel.app</a>.</p></section>
    <section className="panel danger-panel"><h2>Trust assumptions</h2><p>The exchanges may correlate, share infrastructure, become unavailable, or publish abnormal last trades. Validators can time out or reach no majority. Bradbury is a test network. PriceGuard is non-custodial, but its full covenant create/evaluate/expire/acknowledge lifecycle remains unverified.</p></section>
  </div>
}
